export const translations = {
  ar: {
    appName: "شهد",
    appSlogan: "معًا ننمو",
    welcomeMessage: "مرحبًا بكم في شهد",
    welcomeHeader: "مجتمع الأمل والنمو للأيتام في السودان",
    welcomeSubHeader: "منصة شاملة تهدف إلى دعم الأيتام في السودان من خلال التعليم، التواصل، تنمية المواهب، والدعم النفسي. معاً نبني مستقبلاً مشرقاً مليئاً بالأمل والفرص.",
    login: "تسجيل الدخول",
    createAccount: "إنشاء حساب جديد",
    selectRole: "اختر دورك للبدء",
    orphan: "يتيم",
    supervisor: "مشرف",
    volunteer: "متطوع",
    supporter: "داعم",
    home: "الرئيسية",
    community: "مجتمعنا",
    education: "التعليم والنمو",
    support: "الدعم والإرشاد",
    collaboration: "دور الأيتام",
    talentZone: "منطقة المواهب",
    volunteerAndDonate: "التطوع والدعم",
    logout: "تسجيل الخروج",
    successStories: "قصص نجاح",
    dailyHope: "رسالة أمل يومية",
    dailyQuote: "”الأمل هو الحلم الذي يوقظ الروح.“ - أرسطو",
    newActivities: "آخر الأنشطة",
    ourHeroes: "أبطالنا",
    helpCorner: "ركن المساعدة",
    viewAll: "عرض الكل",
    communityHubTitle: "تواصل الأيتام",
    discussions: "النقاشات",
    addTopic: "أضف موضوع",
    shareStory: "شارك قصة",
    communityStats: "إحصائيات المجتمع",
    members: "أعضاء",
    topics: "مواضيع",
    educationTitle: "التعليم المشترك",
    allLessons: "كل الدروس",
    myAchievements: "إنجازاتي",
    myProgress: "تقدمي",
    emotionalIntelligence: "الذكاء العاطفي",
    digitalSkills: "المهارات الرقمية",
    crafts: "الحرف اليدوية",
    financialLiteracy: "الثقافة المالية",
    startLesson: "ابدأ الدرس",
    talentZoneTitle: "منطقة المواهب والإبداع",
    gallery: "معرض الأعمال",
    competitions: "المسابقات",
    addWork: "أضف عملك",
    addCompetition: "أضف مسابقة",
    subscribe: "اشتراك",
    supportTitle: "الدعم والإرشاد النفسي",
    individualCounseling: "الإرشاد الفردي",
    groupSessions: "الجلسات الجماعية",
    resources: "موارد تعليمية",
    bookSession: "احجز جلسة",
    joinSession: "انضم للجلسة",
    download: "تحميل",
    orphanagesDirectory: "دليل دور الأيتام",
    filterByState: "تصفية حسب الولاية",
    allStates: "كل الولايات",
    volunteerTitle: "التطوع",
    donationTitle: "التبرع",
    volunteerOpportunities: "فرص التطوع",
    becomeVolunteer: "كن متطوعاً",
    ourVolunteers: "المتطوعون",
    whyDonate: "لماذا تتبرع؟",
    financialDonation: "تبرع مالي",
    inKindDonation: "تبرع عيني",
    donateNow: "تبرع الآن",
    next: "التالي",
    previous: "السابق",
    finishRegistration: "إكمال التسجيل",
    step1: "اختر دورك",
    step2: "البيانات الأساسية",
    step3: "الاهتمامات والمهارات",
    fullName: "الاسم الكامل",
    emailOrPhone: "البريد الإلكتروني أو رقم الهاتف",
    password: "كلمة المرور",
    selectInterests: "حدد اهتماماتك",
    selectSkills: "حدد مهاراتك",
    art: "الفن",
    programming: "البرمجة",
    sports: "الرياضة",
    reading: "القراءة",
    writing: "الكتابة",
    cooking: "الطبخ",
    gardening: "البستنة",
    music: "الموسيقى",
    communication: "التواصل",
    problemSolving: "حل المشكلات",
    leadership: "القيادة",
    teamwork: "العمل الجماعي",
    creativity: "الإبداع",
    technical: "مهارات تقنية",
    commentPlaceholder: "أضف تعليقاً...",
    postComment: "نشر",
    myProfile: "ملفي الشخصي",
    adminDashboard: "لوحة تحكم المسؤول",
    addYourWorkTitle: "أضف عملك الفني",
    artworkTitle: "عنوان العمل",
    artworkType: "نوع العمل",
    uploadImage: "رفع صورة",
    submit: "إرسال",
    subscribeConfirmation: "تأكيد الاشتراك في المسابقة؟",
    subscribed: "مشترك",
    volunteerRegistration: "تسجيل كمتطوع",
    whyVolunteer: "لماذا تود التطوع؟",
    donationInformation: "معلومات التبرع",
    bankTransfer: "للتبرع المالي، يرجى التحويل إلى الحساب التالي:",
    inKindContact: "للتبرعات العينية، يرجى التواصل معنا لتنسيق الاستلام:",
    myArtworks: "أعمالي الفنية",
    myCompetitions: "مسابقاتي",
    close: "إغلاق",
    addActivity: "إضافة نشاط جديد",
    newActivityTitle: "عنوان النشاط",
    activityDescription: "وصف النشاط",
    activityDescriptionPlaceholder: "ما هو النشاط الجديد؟",
    save: "حفظ",
    followUs: "تابعنا على",
    volunteerSubmissionSuccessTitle: "تم استلام طلبك بنجاح",
    volunteerSubmissionSuccessBody: "شكراً لاهتمامك بالانضمام إلينا. سنتواصل معك قريباً لمناقشة الخطوات التالية.",
    adminTools: "أدوات المسؤول",
    goToAdminDashboard: "الانتقال إلى لوحة التحكم",
    manageContent: "إدارة المحتوى",
    volunteerApplications: "طلبات التطوع",
    noPendingApplications: "لا توجد طلبات تطوع معلقة حالياً.",
    applicationFrom: "طلب من:",
    contactInfo: "معلومات التواصل:",
    reasonForVolunteering: "سبب التطوع:",
    approve: "قبول",
    reject: "رفض",
    donationSummary: "ملخص التبرعات",
    totalFinancial: "إجمالي التبرعات المالية",
    totalInKind: "إجمالي التبرعات العينية",
    items: "عناصر",
    deleteActivity: "حذف النشاط",
  },
  en: {
    appName: "Shahd",
    appSlogan: "Together We Grow",
    welcomeMessage: "Welcome to Shahd",
    welcomeHeader: "The Community of Hope and Growth for Orphans in Sudan",
    welcomeSubHeader: "A comprehensive platform aimed at supporting orphans in Sudan through education, communication, talent development, and psychological support. Together, we build a bright future full of hope and opportunities.",
    login: "Login",
    createAccount: "Create New Account",
    selectRole: "Select your role to start",
    orphan: "Orphan",
    supervisor: "Supervisor",
    volunteer: "Volunteer",
    supporter: "Supporter",
    home: "Home",
    community: "Community Hub",
    education: "Education & Growth",
    support: "Support & Mentorship",
    collaboration: "Orphanages",
    talentZone: "Talent Zone",
    volunteerAndDonate: "Volunteer & Donate",
    logout: "Logout",
    successStories: "Success Stories",
    dailyHope: "Daily Message of Hope",
    dailyQuote: "\"Hope is a waking dream.\" - Aristotle",
    newActivities: "Latest Activities",
    ourHeroes: "Our Heroes",
    helpCorner: "Help Corner",
    viewAll: "View All",
    communityHubTitle: "Orphans' Connect",
    discussions: "Discussions",
    addTopic: "Add Topic",
    shareStory: "Share Story",
    communityStats: "Community Stats",
    members: "Members",
    topics: "Topics",
    educationTitle: "Shared Learning",
    allLessons: "All Lessons",
    myAchievements: "My Achievements",
    myProgress: "My Progress",
    emotionalIntelligence: "Emotional Intelligence",
    digitalSkills: "Digital Skills",
    crafts: "Handicrafts",
    financialLiteracy: "Financial Literacy",
    startLesson: "Start Lesson",
    talentZoneTitle: "Talent & Creativity Zone",
    gallery: "Gallery",
    competitions: "Competitions",
    addWork: "Add Your Work",
    addCompetition: "Add Competition",
    subscribe: "Subscribe",
    supportTitle: "Psychological Support & Mentorship",
    individualCounseling: "Individual Counseling",
    groupSessions: "Group Sessions",
    resources: "Educational Resources",
    bookSession: "Book a Session",
    joinSession: "Join Session",
    download: "Download",
    orphanagesDirectory: "Orphanages Directory",
    filterByState: "Filter by State",
    allStates: "All States",
    volunteerTitle: "Volunteering",
    donationTitle: "Donation",
    volunteerOpportunities: "Volunteer Opportunities",
    becomeVolunteer: "Become a Volunteer",
    ourVolunteers: "Our Volunteers",
    whyDonate: "Why Donate?",
    financialDonation: "Financial Donation",
    inKindDonation: "In-kind Donation",
    donateNow: "Donate Now",
    next: "Next",
    previous: "Previous",
    finishRegistration: "Finish Registration",
    step1: "Choose Your Role",
    step2: "Basic Information",
    step3: "Interests & Skills",
    fullName: "Full Name",
    emailOrPhone: "Email or Phone Number",
    password: "Password",
    selectInterests: "Select Your Interests",
    selectSkills: "Select Your Skills",
    art: "Art",
    programming: "Programming",
    sports: "Sports",
    reading: "Reading",
    writing: "Writing",
    cooking: "Cooking",
    gardening: "Gardening",
    music: "Music",
    communication: "Communication",
    problemSolving: "Problem Solving",
    leadership: "Leadership",
    teamwork: "Teamwork",
    creativity: "Creativity",
    technical: "Technical Skills",
    commentPlaceholder: "Add a comment...",
    postComment: "Post",
    myProfile: "My Profile",
    adminDashboard: "Admin Dashboard",
    addYourWorkTitle: "Add Your Artwork",
    artworkTitle: "Artwork Title",
    artworkType: "Artwork Type",
    uploadImage: "Upload Image",
    submit: "Submit",
    subscribeConfirmation: "Confirm subscription to this competition?",
    subscribed: "Subscribed",
    volunteerRegistration: "Volunteer Registration",
    whyVolunteer: "Why do you want to volunteer?",
    donationInformation: "Donation Information",
    bankTransfer: "For financial donations, please transfer to the following account:",
    inKindContact: "For in-kind donations, please contact us to coordinate pickup:",
    myArtworks: "My Artworks",
    myCompetitions: "My Competitions",
    close: "Close",
    addActivity: "Add New Activity",
    newActivityTitle: "Activity Title",
    activityDescription: "Activity Description",
    activityDescriptionPlaceholder: "What is the new activity?",
    save: "Save",
    followUs: "Follow us on",
    volunteerSubmissionSuccessTitle: "Application Received Successfully",
    volunteerSubmissionSuccessBody: "Thank you for your interest in joining us. We will contact you soon to discuss the next steps.",
    adminTools: "Admin Tools",
    goToAdminDashboard: "Go to Admin Dashboard",
    manageContent: "Manage Content",
    volunteerApplications: "Volunteer Applications",
    noPendingApplications: "There are no pending volunteer applications at this time.",
    applicationFrom: "Application from:",
    contactInfo: "Contact Info:",
    reasonForVolunteering: "Reason for volunteering:",
    approve: "Approve",
    reject: "Reject",
    donationSummary: "Donation Summary",
    totalFinancial: "Total Financial Donations",
    totalInKind: "Total In-Kind Donations",
    items: "Items",
    deleteActivity: "Delete Activity",
  },
};